include("bpdn_model_sampled_sto.jl")
include("group_lasso_model_sto.jl")
include("matrand_model_sto.jl")
include("svm_model_sto.jl")
include("ijcnn1_model_sto.jl")
include("lrcomp_model_sto.jl")
#include("bpdn_model_sampled_prob.jl")